[pytest]
asyncio_mode = auto
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = WARNING

# Ignore deprecation warnings from third-party libs
filterwarnings =
    ignore::DeprecationWarning:chromadb.*:
    ignore::DeprecationWarning:pydantic.*:
